### ISSUE TITLE
OR condition more SQL-like?

### ISSUE THREAD

**Issue by jorainer** [mwang87/MassQueryLanguage_Documentation#2]
I've just seen in the documentation that you support now also OR, which I find actually very nice! 
According to the documentation it is possible to use `MS2PROD=(100 OR 104)` to select data with a peak with m/z 100 or 104. I would find it however more intuitive to express that in a more SQL-like way, i.e. as `MS2PROD = 100 OR MS2PROD = 104`. That way both logical operations `AND` and `OR` would be *at the same level*. Also, I think this would be easier on the parser and would also support constructs such as `MS2PROD=100:TOLERANCEMZ=0.1 OR MS2PROD=104:TOLERANCEMZ=0.2`, i.e. have different tolerances on the individual peaks.

**Comment by mwang87** [comment]
Hi Jo,

Definitely a great idea and things we've been considering for a while. The biggest hurdle in making OR/AND at the same level revolves around order of operations. One thing I did try to avoid is not requiring a huge number of nested parentheses which normally is required in other languages to fully support boolean logic. One alternative is disallowing the ability to mix and match AND/OR operations at the same level and so order does not matter. 

The current approach strikes a balance between the two, where it allows for limited combinations of OR and AND that seemed to cover many of what the users seemed to want to do. 

Let me know what you think about the other suggestions. 

Best,

Ming

**Comment by jorainer** [comment]
Hi Ming,

yes, makes total sense. Thinking it over I believe that can indeed avoid nested statements (which makes it then again complicated for the user).

Will this now be supported for all conditions or only for some (e.g. `MS2PROD`)? Also, how are `TOLERANCEPPM` and `TOLERANCEMZ` used in this scenario? Are they added to each value or only at the end of the condition definition (i.e. `MS2PROD=(100:TOLERANCEPPM=5 OR 104:TOLERANCEPPM=5)` or `MS2PROD=(100 OR 104):TOLERANCEPPM=5`)?

**Comment by mwang87** [comment]
Hi Jo,

So the OR clauses are only supported on the conditions (```MS2PROD```, ```MS1MZ```, ```MS2PREC```) and not the qualifiers (```TOLERANCEPPM```). The qualifiers will apply to all the of the entries. So the last one is correct, ```MS2PROD=(100 OR 104):TOLERANCEPPM=5```

**Comment by jorainer** [comment]
Excellent! Thanks for the clarification!
